---
- name: Install K3S on EC2 Ubuntu based
  hosts: ec2_node
  gather_facts: true
  vars:
    ec2_user: ubuntu
  become: true

  tasks:
    - name: Ensure inventory is loaded
      set_fact:
        ansible_inventory_file: /home/dxs01/finalSolution/ansible_playbooks/invenory

    - name: Update apt
      apt:
        update_cache: yes

    - name: Ensure Python is installed for Ansible
      package:
        name:
          - python3
          - python3-pip
          - python3-kubernetes
        state: present

    - name: Ensure the ubuntu user is in the sudo group
      user:
        name: ubuntu
        groups: sudo
        append: yes

    - name: Install K3s on the node
      shell: "curl -sfL https://get.k3s.io | sh -"
      register: k3s_install
      delegate_to: "{{ inventory_hostname }}"
      vars:
        ansible_ssh_private_key_file: "/home/dxs01/finalSolution/terraform/my_key_pair.pem"

    - name: Wait for K3s to be ready
      command: kubectl get nodes --kubeconfig /etc/rancher/k3s/k3s.yaml
      register: k3s_status
      retries: 10
      delay: 10
      until: k3s_status.rc == 0
      changed_when: false
      delegate_to: "{{ inventory_hostname }}"
      vars:
        ansible_ssh_private_key_file: "/home/dxs01/finalSolution/terraform/my_key_pair.pem"

    - name: Output K3s status
      debug:
        msg: "K3s installation is complete. Node status: {{ k3s_status.stdout }}"
      delegate_to: "{{ inventory_hostname }}"
      vars:
        ansible_ssh_private_key_file: "/home/dxs01/finalSolution/terraform/my_key_pair.pem"

    - name: Create .kube directory for ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Copy kubeconfig to ubuntu user's home directory
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: "0644"
        remote_src: yes

    - name: Set KUBECONFIG environment variable for ubuntu user
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: "export KUBECONFIG=/home/ubuntu/.kube/config"
      delegate_to: "{{ inventory_hostname }}"
