---
- name: Fetch kubeconfig and inject to GitHub repository
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:
    - name: Fetch Terraform output
      command: terraform output -json
      args:
        chdir: "{{ terraform_dir }}"
      register: tf_output

    - name: Set public IP fact
      set_fact:
        ec2_host: "{{ tf_output.stdout | from_json | json_query('instance_public_ip.value') }}"
      when: tf_output.stdout != "{}"
    - name: Fail if public IP is not set
      fail:
        msg: "Public IP not found in Terraform output."
      when: ec2_host == ""

    - name: KUBECONFIG RAW
      shell: cat "{{ kubeconfig_path }}"
      register: kubeconfig_content
      become: yes
      delegate_to: "{{ ec2_user }}@{{ ec2_host }}"
      vars:
        ansible_ssh_private_key_file: "/home/dxs01/finalSolution/terraform/my_key_pair.pem"

    - name: Base64 encode kubeconfig content (for GitHub Secret)
      set_fact:
        kubeconfig: "{{ kubeconfig_content.stdout }}"

    - name: Save base64 encoded kubeconfig to a local file
      copy:
        content: "{{ kubeconfig }}"
        dest: "/home/dxs01/finalSolution/ansible_playbooks/kubeconfig.txt"
      when: kubeconfig_content.stdout != ""

    - name: Display non-base64 encoded kubeconfig content
      debug:
        var: kubeconfig_content.stdout
