---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rn-jesus-deploy
  labels:
    app: rn-jesus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rn-jesus
  template:
    metadata:
      labels:
        app: rn-jesus
    spec:
      containers:
        - name: rn-jesus-container
          image: dxs01/rn_jesus:latest #  TAG ISSUE
          ports:
            - containerPort: 3000
