---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rn-jesus
  name: rn-jesus-deploy
  namespace: rn-jesus
  annotations:
    argocd-image-updater.argoproj.io/image-list: dxs01/rn_jesus
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-cred
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rn-jesus
  template:
    metadata:
      labels:
        app: rn-jesus
    spec:
      containers:
        - image: dxs01/rn_jesus:latest
          name: rn-jesus-container
          ports:
            - containerPort: 3000
