name: Deploy to Kubernetes

on:
  push:
    branches: [main, Testing]

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download public IP from S3
        run: |
          aws s3 cp s3://rnj-bucket/terraform_outputs.json ./terraform_outputs.json

      - name: Read the public IP
        run: |
          export PUBLIC_IP=$(jq -r '.instance_public_ip.value' terraform_outputs.json)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Sudo checkout
        run: |
          echo "$(whoami) ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
      - name: Create kubeconfig
        run: |
          mkdir -p ~/home/ubuntu/.kube 
          kubectl config view --raw > ~/home/ubuntu/.kube/config

      - name: Replace Public IP in Ingress Manifest
        run: |
          sed -i "s/\${PUBLIC_IP}/$PUBLIC_IP/g" k8s/ingress.yml

      - name: ingress
        run: |
          kubectl apply -f k8s/ingress.yml
      - name: service
        run: |
          kubectl apply -f k8s/service.yml

      - name: deploy
        run: |
          kubectl apply -f k8s/deploy.yml
