name: Deploy to Kubernetes

on:
  push:
    branches: main

permissions:
  actions: write
  contents: read

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure AWS CLI output to JSON
        run: aws configure set output json

      - name: Read the public IP
        run: |
          export PUBLIC_IP=$(jq -r '.instance_public_ip.value' terraform_outputs.json)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Configure kubectl to skip TLS verification
        run: |
          kubectl config set-cluster my-cluster --server=https://$PUBLIC_IP:6443 --insecure-skip-tls-verify=true
        env:
          PUBLIC_IP: ${{ env.PUBLIC_IP }}

      - name: Set up Kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Get latest image SHA256 digest
        run: |
          export LATEST_SHA=$(curl -s https://registry.hub.docker.com/v2/repositories/dxs01/rn_jesus/tags | jq -r '.results[0].name')
          echo "LATEST_SHA=$LATEST_SHA" >> $GITHUB_ENV

      - name: Create namespace
        continue-on-error: true
        run: |
          kubectl create namespace rn-jesus

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v5
        with:
          action: deploy
          manifests: k8s/
          images: |
            dxs01/rn_jesus:${{ env.LATEST_SHA }}
          imagepullsecrets: |
            DOCKER_PASSWORD
          namespace: rn-jesus
          skip-tls-verify: true

      - name: Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
