name: Deploy to Kubernetes

on:
  push:
    branches: main

permissions:
  actions: write
  contents: read

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download Terraform configuration from S3
        run: |
          aws s3 cp s3://rnj-bucket/terraform/ ./terraform/ --recursive

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.10.5

      - name: Terraform Init
        run: terraform init -chdir=./terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan -chdir=./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan -chdir=./terraform

      - name: Get latest image SHA256 digest
        run: |
          export LATEST_SHA=$(curl -s https://registry.hub.docker.com/v2/repositories/dxs01/rn_jesus/tags | jq -r '.results[0].name')
          echo "LATEST_SHA=$LATEST_SHA" >> $GITHUB_ENV

      - name: Create namespace
        continue-on-error: true
        run: |
          kubectl create namespace rn-jesus --insecure-skip-tls-verify

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v5
        with:
          action: deploy
          manifests: k8s/
          images: |
            dxs01/rn_jesus:${{ env.LATEST_SHA }}
          imagepullsecrets: |
            DOCKER_PASSWORD
          namespace: rn-jesus
          skip-tls-verify: true

      - name: Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
