name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1

      - name: Download public IP from S3
        run: |
          aws s3 cp s3://rnj-bucket/public_ip.txt ./public_ip.txt

      - name: Read the public IP
        run: |
          export PUBLIC_IP=$(cat public_ip.txt)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Create kubeconfig
        run: |
          mkdir -p ${HOME}/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config

      - name: Replace Public IP in Ingress Manifest
        run: |
          sed -i "s/\${PUBLIC_IP}/$PUBLIC_IP/g" k8s/ingress.yml

      - name: Create context
        run: |
          kubectl config set-context rn-jesus-context --cluster=your-cluster-rn-jesus --user=jesus --namespace=rn-jesus

      - name: Use context
        run: kubectl config use-context rn-jesus-context

      - name: Deploy to K8s
        run: kubectl apply -f k8s/
