name: Deploy to Kubernetes

on:
  push:
    branches: [main, Testing]

permissions:
  actions: write
  contents: read

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download public IP from S3
        run: |
          aws s3 cp s3://rnj-bucket/terraform_outputs.json ./terraform_outputs.json
      - name: Test
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBE_CONFIG }}  > ${HOME}/.kube/config  #I COMPLETELY FORGOT ABOUT THE GHactions secret !!
          cat ${HOME}/.kube/config

      - name: Read the public IP
        run: |
          export PUBLIC_IP=$(jq -r '.instance_public_ip.value' terraform_outputs.json)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Replace Public IP in Ingress Manifest
        run: |
          sed -i "s/\${PUBLIC_IP}/$PUBLIC_IP/g" k8s/ingress.yml

      - name: Service manifest
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          kubectl apply -f k8s/service.yml
          kubectl get nodes -v=10
      - name: Deployment manifest
        run: |
          kubectl apply -f k8s/deploy.yml --validate=false
      - name: Ingress manifest
        run: |
          kubectl apply -f k8s/ingress.yml --validate=false
