name: Deploy to Kubernetes

on:
  push:
    branches: [main, Testing]

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download public IP from S3
        run: |
          aws s3 cp s3://rnj-bucket/terraform_outputs.json ./terraform_outputs.json

      - name: Read the public IP
        run: |
          export PUBLIC_IP=$(jq -r '.instance_public_ip.value' terraform_outputs.json)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Create kubeconfig
        run: |
          sudo mkdir -p ${HOME}/.kube
          sudo echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config

      - name: Replace Public IP in Ingress Manifest
        run: |
          sudo sed -i "s/\${PUBLIC_IP}/$PUBLIC_IP/g" k8s/ingress.yml

      - name: Create context
        run: |
          sudo kubectl config set-context rn-jesus-context --cluster=your-cluster-rn-jesus --user=jesus --namespace=rn-jesus

      - name: Use context
        run: sudo kubectl config use-context rn-jesus-context

      - name: Deploy to K8s
        run: sudo kubectl apply -f k8s/

      - name: Enable Debugging
        run: |
          set -x
          export KUBECONFIG=${HOME}/.kube/config
          kubectl version --client
          kubectl config view
          kubectl config get-contexts
          kubectl config current-context
